
package java_with_sqlserver_Gui;

import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class Jdbc_swings extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public Jdbc_swings() {
        initComponents();
        populateTable();
        
    }
    public void populateTable(){
        model=(DefaultTableModel)tblsql.getModel();
        model.setRowCount(0);
        try {
            ArrayList<HarfNotAgirlik> dersnotu=getHarfNotu();
            for(HarfNotAgirlik harfna :dersnotu){
                Object[] row =
                {harfna.getHarfnotu(),harfna.getAgirlik(),harfna.getTaban(),harfna.getTavan()};
                        
                model.addRow(row);
            }
            
        } catch (SQLException ex) {
        }
    }

    public ArrayList<HarfNotAgirlik> getHarfNotu() throws SQLException{
        Connection connection=null;
        
        DBHelper dbhelper = new DBHelper();
        
        Statement statement = null;
        ResultSet rs;
        ArrayList<HarfNotAgirlik> harfna=null;
        
        try {
           connection=dbhelper.getConnection();
           statement = connection.createStatement();
           rs=statement.executeQuery("select * from HarfNotAgirlik");
           harfna=new ArrayList<HarfNotAgirlik>();
           while(rs.next()){
            harfna.add(new HarfNotAgirlik(rs.getString("HarfNotu"),rs.getInt("Taban"),rs.getInt("Agirlik"),rs.getInt("Tavan")));
        }
        } catch (SQLException exception) {
            dbhelper.showErrorMessage(exception);
            
        }finally{
            statement.close();
            connection.close();
        }return harfna;
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsql = new javax.swing.JTable();
        txtSearch = new java.awt.TextField();
        lblSearch = new java.awt.Label();
        tbxharfnotu = new javax.swing.JLabel();
        tbxtaban = new javax.swing.JLabel();
        tbxtavan = new javax.swing.JLabel();
        lblHarfNotu = new javax.swing.JTextField();
        lblTabanNot = new javax.swing.JTextField();
        lblTavanNot = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        tbxAgirlik = new javax.swing.JLabel();
        lblagirlik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tblsql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HarfNotu", "Agirlik", "Taban", "Tavan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblsql);
        if (tblsql.getColumnModel().getColumnCount() > 0) {
            tblsql.getColumnModel().getColumn(0).setResizable(false);
            tblsql.getColumnModel().getColumn(1).setResizable(false);
            tblsql.getColumnModel().getColumn(2).setResizable(false);
            tblsql.getColumnModel().getColumn(3).setResizable(false);
        }

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("Arama:");

        tbxharfnotu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxharfnotu.setForeground(new java.awt.Color(255, 255, 255));
        tbxharfnotu.setText("Harfnotu:");

        tbxtaban.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxtaban.setForeground(new java.awt.Color(255, 255, 255));
        tbxtaban.setText("Taban Not:");

        tbxtavan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxtavan.setForeground(new java.awt.Color(255, 255, 255));
        tbxtavan.setText("Tavan Not:");

        lblHarfNotu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTabanNot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTavanNot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnADD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnADD.setText("ekle");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        tbxAgirlik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxAgirlik.setForeground(new java.awt.Color(255, 255, 255));
        tbxAgirlik.setText("Ağırlık:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbxtaban)
                                    .addComponent(tbxAgirlik, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblagirlik, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(lblTabanNot)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbxtavan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(lblTavanNot, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbxharfnotu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(lblHarfNotu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxharfnotu)
                    .addComponent(lblHarfNotu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnADD))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbxAgirlik)
                    .addComponent(lblagirlik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxtaban)
                    .addComponent(lblTabanNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTavanNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxtavan))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String searchkey=txtSearch.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(model);
        tblsql.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchkey));
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
       Connection connection=null;
        
       DBHelper dbhelper = new DBHelper();
       PreparedStatement statement= null;
        try {
            connection=dbhelper.getConnection();
            String sql="insert into HarfNotAgirlik(HarfNotu,Agirlik,Taban,Tavan) values(?,?,?,?)";
            statement=connection.prepareStatement(sql);
            statement.setString(1,tbxharfnotu.getText());
            statement.setDouble(2, Double.valueOf(tbxAgirlik.getText()));
            statement.setInt(3,Integer.valueOf(tbxtaban.getText()));
            statement.setInt(4,Integer.valueOf(tbxtavan.getText()));
            int result=statement.executeUpdate();
            populateTable();
            
            
        } catch (SQLException exception) {
            dbhelper.showErrorMessage(exception);
        }finally{
           try {
               statement.close();
               connection.close();
           } catch (SQLException ex) {
              
           }
        }
       
    }//GEN-LAST:event_btnADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jdbc_swings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jdbc_swings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jdbc_swings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jdbc_swings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jdbc_swings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblHarfNotu;
    private java.awt.Label lblSearch;
    private javax.swing.JTextField lblTabanNot;
    private javax.swing.JTextField lblTavanNot;
    private javax.swing.JTextField lblagirlik;
    private javax.swing.JTable tblsql;
    private javax.swing.JLabel tbxAgirlik;
    private javax.swing.JLabel tbxharfnotu;
    private javax.swing.JLabel tbxtaban;
    private javax.swing.JLabel tbxtavan;
    private java.awt.TextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private ArrayList<HarfNotAgirlik> getDersnotu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void getAgirlik() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
